from model.user import User
from model.module import Module
from model.challenge import Challenge
from model.progress import Progress
from model.conversation import Conversation
from model.message import Message
from model.feedback import Feedback
from model.diagnostic import Diagnostic
from model.student_profile import StudentProfile